baseURL = "https://ColumbiaSC-Tech.github.io/"
languageCode = "en-us"
title = "ColumbiaSC-Tech"
theme = "hugo-theme-nix"

[params]
  GithubID = "ColumbiaSC-Tech"
  SlackURL = "https://join.slack.com/t/columbiasc-tech/shared_invite/enQtMjYzOTU5NTExNjY1LWUwYmI4NjJiNmYwMDhhYWY3MTgyMDc4NDkyOGZiYmEyNjE1MGM3MmM2NTFiMDlkYWRiNTAyZjRlODNkZjNmOWY"
  #GitlabId = "your_gitlab"
  #TwitterID = "your_twitter"
  #CodepenID = "your_codepen"
  #LinkedInID = "your_linkedin"
  #GoogleplusID = "your_googleplus"
  FacebookID = "499195467115318"
  Name = "ColumbiaSC-Tech"
  HeaderUsername = "tech"
  HeaderHostname = "cola"
  #Email = "your_email"
  About = "Welcome to ColumbiaSC-Tech! Feel free to join us in the above communities by clicking above."
  ProfilePicture = "Scstatehouse.jpg"
  #GoogleAnalytics = "your_google_analytics_id"
